// Mock data for STARDUST AI Revenue Recovery Dashboard

export const metricCardsData = [
  {
    id: "risk",
    label: "REVENUE AT RISK",
    value: "₹12.4L",
    change: "+14.2% from yesterday",
    trend: "increase", // shows risk is accumulating
    icon: "AlertTriangle",
  },
  {
    id: "recovered",
    label: "RECOVERED",
    value: "₹4.8L",
    change: "+8.3% this week",
    trend: "increase", // positive trend
    icon: "ShieldCheck",
  },
  {
    id: "cases",
    label: "ACTIVE CASES",
    value: "38",
    change: "12 flagged as High Risk",
    trend: "stable",
    icon: "Activity",
  },
  {
    id: "rate",
    label: "RECOVERY RATE",
    value: "68.4%",
    change: "+2.1% this month",
    trend: "increase",
    icon: "Zap",
  },
];

export const recoveryChartData = [
  { day: "Aug 14", atRisk: 8.2, inRecovery: 4.1, recovered: 2.8 },
  { day: "Aug 15", atRisk: 9.5, inRecovery: 5.4, recovered: 3.2 },
  { day: "Aug 16", atRisk: 11.1, inRecovery: 6.8, recovered: 3.8 },
  { day: "Aug 17", atRisk: 10.4, inRecovery: 7.2, recovered: 4.1 },
  { day: "Aug 18", atRisk: 12.1, inRecovery: 8.0, recovered: 4.3 },
  { day: "Aug 19", atRisk: 11.5, inRecovery: 7.8, recovered: 4.5 },
  { day: "Aug 20", atRisk: 13.0, inRecovery: 8.9, recovered: 4.6 },
  { day: "Aug 21", atRisk: 12.2, inRecovery: 9.1, recovered: 4.7 },
  { day: "Aug 22", atRisk: 12.4, inRecovery: 9.3, recovered: 4.8 },
];

export const initialActivityData = [
  {
    id: 1,
    time: "12:35:10",
    type: "DETECTED",
    status: "Payment failure",
    amount: "₹18,400",
    customer: "Acme Corp",
    detail: "Decline code: Insufficient funds",
  },
  {
    id: 2,
    time: "12:35:12",
    type: "DIAGNOSED",
    status: "Insufficient funds",
    amount: "₹18,400",
    customer: "Acme Corp",
    detail: "Routing profile suggests retry at 14:00 optimal window",
  },
  {
    id: 3,
    time: "12:35:15",
    type: "ACTION",
    status: "Retry scheduled",
    amount: "₹18,400",
    customer: "Acme Corp",
    detail: "Smart queue intervention active",
  },
  {
    id: 4,
    time: "12:36:20",
    type: "RECOVERED",
    status: "Recovered",
    amount: "₹18,400",
    customer: "Acme Corp",
    detail: "Payment retry successful",
  },
  {
    id: 5,
    time: "12:30:14",
    type: "DETECTED",
    status: "Subscription Failed",
    amount: "₹9,800",
    customer: "Nova Labs",
    detail: "Decline code: Card expired or invalid",
  },
  {
    id: 6,
    time: "12:30:18",
    type: "DIAGNOSED",
    status: "Expired Card",
    amount: "₹9,800",
    customer: "Nova Labs",
    detail: "Account updater protocol activated",
  },
  {
    id: 7,
    time: "12:31:02",
    type: "ACTION",
    status: "Smart Retry",
    amount: "₹9,800",
    customer: "Nova Labs",
    detail: "Triggered email update link + fallback smart payment link",
  },
  {
    id: 8,
    time: "12:15:30",
    type: "DETECTED",
    status: "Invoice Overdue",
    amount: "₹42,000",
    customer: "Vertex Systems",
    detail: "Payment term +15 days exceeded",
  },
  {
    id: 9,
    time: "12:16:00",
    type: "DIAGNOSED",
    status: "Overdue Invoice",
    amount: "₹42,000",
    customer: "Vertex Systems",
    detail: "High-value business profile, direct contact recommended",
  },
  {
    id: 10,
    time: "12:16:15",
    type: "ACTION",
    status: "Receivables Chase",
    amount: "₹42,000",
    customer: "Vertex Systems",
    detail: "Escalated: Autonomous billing dispatch sent to finance team",
  },
];

export const riskTableData = [
  {
    id: "case-01",
    customer: "Acme Corp",
    issue: "Payment Failed",
    amount: "₹18,400",
    risk: "High",
    action: "Retry + Email",
    status: "Recovering",
  },
  {
    id: "case-02",
    customer: "Nova Labs",
    issue: "Subscription Failed",
    amount: "₹9,800",
    risk: "Medium",
    action: "Smart Retry",
    status: "Pending",
  },
  {
    id: "case-03",
    customer: "Vertex Systems",
    issue: "Invoice Overdue",
    amount: "₹42,000",
    risk: "High",
    action: "Receivables Chase",
    status: "Escalated",
  },
  {
    id: "case-04",
    customer: "Quantum Edge",
    issue: "Card Expired",
    amount: "₹15,200",
    risk: "Low",
    action: "Account Updater",
    status: "Recovered",
  },
  {
    id: "case-05",
    customer: "Apex Dynamics",
    issue: "Auth Required",
    amount: "₹24,500",
    risk: "Medium",
    action: "Smart Retry + SMS",
    status: "Recovering",
  },
  {
    id: "case-06",
    customer: "Sentinel Tech",
    issue: "Insufficient Funds",
    amount: "₹31,000",
    risk: "High",
    action: "Optimal Hour Retry",
    status: "Pending",
  },
  {
    id: "case-07",
    customer: "Nebula Ventures",
    issue: "Network Decline",
    amount: "₹8,400",
    risk: "Low",
    action: "Immediate Retry",
    status: "Recovered",
  },
];

// Additional feed events for simulation
export const simulatorEvents = [
  {
    type: "DETECTED",
    status: "Failed payment detected",
    amount: "₹14,500",
    customer: "Chronos Labs",
    detail: "Decline code: Do not honor",
  },
  {
    type: "DIAGNOSED",
    status: "Suspected network issue",
    amount: "₹14,500",
    customer: "Chronos Labs",
    detail: "Bank server responding with latency. Queue retry.",
  },
  {
    type: "ACTION",
    status: "Retrying card process",
    amount: "₹14,500",
    customer: "Chronos Labs",
    detail: "Routing through secondary Razorpay merchant gateway",
  },
  {
    type: "RECOVERED",
    status: "Revenue recovered successfully",
    amount: "₹14,500",
    customer: "Chronos Labs",
    detail: "Secondary route successful, invoice marked paid",
  },
  {
    type: "DETECTED",
    status: "Subscription billing failed",
    amount: "₹21,000",
    customer: "Sora Media",
    detail: "Card limit exceeded error",
  },
  {
    type: "DIAGNOSED",
    status: "Insufficient limit",
    amount: "₹21,000",
    customer: "Sora Media",
    detail: "Customer credit limit reached. Notify via email.",
  },
  {
    type: "ACTION",
    status: "Payment link dispatch",
    amount: "₹21,000",
    customer: "Sora Media",
    detail: "Sent direct UPI fallback checkout page",
  },
  {
    type: "RECOVERED",
    status: "UPI payment confirmed",
    amount: "₹21,000",
    customer: "Sora Media",
    detail: "Recovered via UPI transaction ID: pay_9281a",
  },
];
